from typing import Iterator

class Engine:
    @staticmethod
    def load(model_path: str) -> "Engine": ...
    def complete(self, prompt: str, *, max_tokens: int = 512, temperature: float = 0.0) -> str: ...
    def stream(self, prompt: str, *, max_tokens: int = 512, temperature: float = 0.0) -> Iterator[str]: ...
